# Generated by Django 4.0.3 on 2022-03-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
